[package]
name = "grfrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "grfrs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"

[profile.release]
codegen-units = 1
lto = "fat"
